# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YrtJYxz9vPQIsWp-qHJFF9CWzcVPf_4B
"""

import pandas as pd
import numpy as np
df = pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Financial%20Market%20News.csv',encoding="iso-8859-1")
df.head()
df.info()
df.shape
df.columns
' '.join(str(X) for X in df.iloc[1,2:27])
df.index
len(df.index)
news=[]
for row in range(0,len(df.index)):
    news.append(' '.join(str(x) for x in df.iloc[row,2:27]))
type(news)
list
news[0]
X = news
type(X)
list
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(lowercase=True, ngram_range=(1,1))
X = cv.fit_transform(X)
X.shape
(4101,48527)
y = df['Label']
y.shape
(4101,)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 2529)
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X_train, y_train)
RandomForestClassifier(n_estimators=200)
y_pred = rf.predict(X_test)
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
confusion_matrix(y_test, y_pred)
print(classification_report(y_test, y_pred))